

person:
  age: 20
  boss: false
  birth: 2017/11/12
  maps: {k1: v1, k2: v2}
  #数组
  lists:
    - l1
    - l2
  dog:
    name: 小狗
    age: 2
  name: zhangsan


#server:
#  port: 8080
#spring:
#  profiles:
#    active: dev

---
server:
  port: 8084
spring:
  profiles: dev


---
server:
  port: 8085
spring:
  profiles: prod


---
server:
  port: 8086
spring:
  profiles: test