server:
  port: 8761
eureka:
  instance:
    appname: eureka-server #eureka实例主机名
    hostname: localhost
  client:
    register-with-eureka: false #不把server注册到eureka上
    fetch-registry: false #不从eureka上来获取服务的注册信息
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
