server:
  port: 8082
spring:
  application:
    name: ticket-consumer
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
  instance:
    prefer-ip-address: true

