server:
  port: 8081
spring:
  application:
    name: ticket-provider
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true #注册服务的时候使用ip进行注册
